---

- name: Setup Vprofile Bastian Host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC Setup variable
      include_vars: vars/bastian_Setup

    - name: Import VPC Setup variable
      include_vars: vars/output_vars


    - name: Create vprofile ec2 key
      ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: key_out



    - name: Save Private key into file bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed



    - name: Create sec grp for bastian host
      ec2_group:
        name: Bastian-host-sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
        register: BastianSG_out


    - name: Creating Bastian Host
      ec2:
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastian_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Bastian_host"
          Project: Vprofile
          Owner: Devops Team
        exact_count: 1
        count_tag:
          Name: "Bastian_host"
          Project: Vprofile
          Owner: Devops Team
        group_id: "{{BastianSG_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastianHost_out
